[pytest]
DJANGO_SETTINGS_MODULE = letraz_server.settings
python_files = test_*.py
markers =
    unit: unit tests
    integration: integration tests
    api: API tests
    model: model tests
    view: view tests
    serializer: serializer tests
    middleware: middleware tests 