# Generated by Django 5.2.4 on 2025-08-02 08:11

import CORE.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='The ISO 3166-1 alpha-3 code of the country.', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the country.', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the process entry.', primary_key=True, serialize=False)),
                ('util_id', models.CharField(blank=True, help_text='Unique process identifier generated by utils-service', max_length=60, null=True)),
                ('desc', models.CharField(help_text='Description of the process.', max_length=250)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('FAILURE', 'Failed'), ('SUCCESS', 'Success'), ('OTHER', 'Others')], default='INITIATED', help_text='The status of the process.', max_length=15)),
                ('status_details', models.CharField(blank=True, help_text='Reason of the current status for process.', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the skill entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the skill entry was last updated.')),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the waitlist entry.', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='The email of the user who joined the waitlist.', max_length=254, unique=True)),
                ('referrer', models.CharField(default='website', help_text='The referrer of the user who joined the waitlist. Usually the source they have come from.', max_length=50)),
                ('waiting_number', CORE.models.AutoIncrementWaitingNumberField(editable=False, help_text='The waiting number of the user who joined the waitlist.')),
                ('has_access', models.BooleanField(default=False, help_text='Whether the user has been granted access to the platform.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp at which the user joined the waitlist.')),
            ],
            options={
                'db_table': 'waitlist',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the experience entry.', primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, help_text='The category of the skill. (optional)', max_length=50, null=True)),
                ('name', models.CharField(help_text='The name of the skill.', max_length=250)),
                ('preferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the skill entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the skill entry was last updated.')),
                ('alias', models.ManyToManyField(blank=True, related_name='alias_skills', to='CORE.skill')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
    ]
