# Generated by Django 5.1.4 on 2025-07-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='has_access',
            field=models.BooleanField(default=False, help_text='Whether the user has been granted access to the platform.'),
        ),
    ]
