# Generated by Django 5.1.4 on 2025-07-22 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0002_waitlist_has_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the process entry.', primary_key=True, serialize=False)),
                ('util_id', models.CharField(blank=True, help_text='Unique process identifier generated by utils-service', max_length=60, null=True)),
                ('desc', models.CharField(help_text='Description of the process.', max_length=250)),
                ('status', models.CharField(choices=[('I', 'Initiated'), ('A', 'Accepted'), ('R', 'Rejected'), ('F', 'Failed'), ('S', 'Success'), ('O', 'Others')], default='I', help_text='The status of the process.', max_length=1)),
                ('status_details', models.CharField(blank=True, help_text='Reason of the current status for process.', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the skill entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the skill entry was last updated.')),
            ],
        ),
    ]
