# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import letraz_utils_pb2 as letraz__utils__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in letraz_utils_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScraperServiceStub(object):
    """===== SERVICES =====

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScrapeJob = channel.unary_unary(
                '/letraz.v1.ScraperService/ScrapeJob',
                request_serializer=letraz__utils__pb2.ScrapeJobRequest.SerializeToString,
                response_deserializer=letraz__utils__pb2.ScrapeJobResponse.FromString,
                _registered_method=True)


class ScraperServiceServicer(object):
    """===== SERVICES =====

    """

    def ScrapeJob(self, request, context):
        """Scrape a job posting from a URL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScraperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScrapeJob': grpc.unary_unary_rpc_method_handler(
                    servicer.ScrapeJob,
                    request_deserializer=letraz__utils__pb2.ScrapeJobRequest.FromString,
                    response_serializer=letraz__utils__pb2.ScrapeJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'letraz.v1.ScraperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('letraz.v1.ScraperService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScraperService(object):
    """===== SERVICES =====

    """

    @staticmethod
    def ScrapeJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/letraz.v1.ScraperService/ScrapeJob',
            letraz__utils__pb2.ScrapeJobRequest.SerializeToString,
            letraz__utils__pb2.ScrapeJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ResumeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TailorResume = channel.unary_unary(
                '/letraz.v1.ResumeService/TailorResume',
                request_serializer=letraz__utils__pb2.TailorResumeRequest.SerializeToString,
                response_deserializer=letraz__utils__pb2.TailorResumeResponse.FromString,
                _registered_method=True)
        self.GenerateScreenshot = channel.unary_unary(
                '/letraz.v1.ResumeService/GenerateScreenshot',
                request_serializer=letraz__utils__pb2.ResumeScreenshotRequest.SerializeToString,
                response_deserializer=letraz__utils__pb2.ResumeScreenshotResponse.FromString,
                _registered_method=True)


class ResumeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TailorResume(self, request, context):
        """Tailor a resume for a specific job posting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateScreenshot(self, request, context):
        """Generate a screenshot of a resume
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResumeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TailorResume': grpc.unary_unary_rpc_method_handler(
                    servicer.TailorResume,
                    request_deserializer=letraz__utils__pb2.TailorResumeRequest.FromString,
                    response_serializer=letraz__utils__pb2.TailorResumeResponse.SerializeToString,
            ),
            'GenerateScreenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateScreenshot,
                    request_deserializer=letraz__utils__pb2.ResumeScreenshotRequest.FromString,
                    response_serializer=letraz__utils__pb2.ResumeScreenshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'letraz.v1.ResumeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('letraz.v1.ResumeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResumeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TailorResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/letraz.v1.ResumeService/TailorResume',
            letraz__utils__pb2.TailorResumeRequest.SerializeToString,
            letraz__utils__pb2.TailorResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateScreenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/letraz.v1.ResumeService/GenerateScreenshot',
            letraz__utils__pb2.ResumeScreenshotRequest.SerializeToString,
            letraz__utils__pb2.ResumeScreenshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/letraz.v1.HealthService/HealthCheck',
                request_serializer=letraz__utils__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=letraz__utils__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=letraz__utils__pb2.HealthCheckRequest.FromString,
                    response_serializer=letraz__utils__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'letraz.v1.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('letraz.v1.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/letraz.v1.HealthService/HealthCheck',
            letraz__utils__pb2.HealthCheckRequest.SerializeToString,
            letraz__utils__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
