### GET user by id API
GET https://{{url}}/api/v1/user/
Authorization: Bearer {{token}}

### Update user by id API
PATCH https://{{url}}/api/v1/user/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": null,
  "first_name": "First Name",
  "last_name": "Last Name",
  "email": "user@letraz.app",
  "phone": 9876543210,
  "dob": null,
  "nationality": null,
  "address": null,
  "city": null,
  "postal": null,
  "country": null,
  "website": null,
  "profile_text": null
}