class ErrorCode:
    INVALID = 'INVALID'
    INVALID_REQUEST = 'INVALID REQUEST'
    GENERIC_EXCEPTION = 'GENERIC EXCEPTION'
    NOT_FOUND = 'RESOURCE NOT FOUND'
    ALREADY_EXISTS = 'RESOURCE EXISTS ALREADY'
    INTERNAL_SERVER_ERROR = 'INTERNAL SERVER ERROR'
    UNAUTHORIZED = 'UNAUTHORIZED'

