### Health Check API
GET https://{{url}}/api/v1/health/

### Error Example API
GET https://{{url}}/api/v1/error-example/

### Error List Example API
GET https://{{url}}/api/v1/error-list-example/

### Get All Waitlist API
GET https://{{url}}/api/v1/waitlist/

### Create Waitlist API
POST https://{{url}}/api/v1/waitlist/
Content-Type: application/json

{
    "email": "test2@letraz.app",
    "referrer": "website"
}

### Get all global skills API
GET https://{{url}}/api/v1/skill/

### Get all global skill categories API
GET https://{{url}}/api/v1/skill/categories
