### Resume ###
### GET All Resume for user API
GET https://{{url}}/api/v1/resume/
Authorization: Bearer {{token}}

### GET Base Resume for user API
GET https://{{url}}/api/v1/resume?base=true
Authorization: Bearer {{token}}

### GET Resume by id API
GET https://{{url}}/api/v1/resume/{{resume_id}}/
Authorization: Bearer {{token}}

### Education ###
### GET All Education by resume id API
GET https://{{url}}/api/v1/resume/{{resume_id}}/education/
Authorization: Bearer {{token}}

### GET Education by id API
GET https://{{url}}/api/v1/resume/{{resume_id}}/education/{{education_id}}/
Authorization: Bearer {{token}}

### Create Education API
POST https://{{url}}/api/v1/resume/{{resume_id}}/education/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "institution_name": "Vidyalankar Institute of Technology",
  "field_of_study": "Electronics",
  "degree": "Bachelor of Engineering",
  "country":"IND",
  "started_from_month": null,
  "started_from_year": null,
  "finished_at_month": null,
  "finished_at_year": null,
  "current": false,
  "description": "CSE"
}

### Delete Education API
DELETE https://{{url}}/api/v1/resume/{{resume_id}}/education/{{education_id}}/
Authorization: Bearer {{token}}

### Experience ###
### GET All Experience by resume id API
GET https://{{url}}/api/v1/resume/{{resume_id}}/experience/
Authorization: Bearer {{token}}

### GET Experience by id API
GET https://{{url}}/api/v1/resume/{{resume_id}}/experience/{{experience_id}}/
Authorization: Bearer {{token}}

### GET Experience by id API
POST https://{{url}}/api/v1/resume/{{resume_id}}/experience/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "resume_section": "b604e2bb-200d-4ee9-b7fc-3348ec9d4d2b",
    "company_name": "Zillow Group",
    "job_title": "Senior Software Engineer",
    "employment_type": "flt",
    "city": "New York",
    "country": null,
    "started_from_month": null,
    "started_from_year": null,
    "finished_at_month": null,
    "finished_at_year": null,
    "current": false,
    "description": "o Leading and mentoring a team of developers across fullstack to support and enhance NYC's leading real \r\nestate marketplace StreetEasy.\r\no Design architecture for internal management tools, digital ad products, authentication, logging and consolidated billing system to provide scalable tools for smooth and convenient real estate buying/renting experience, marketing and communication tool for real estate agents and brokers.\r\no Stack – Ruby on Rails (w/ GraphQL API), JavaScript (w/ ReactJS), CSS, MySQL, Elasticsearch"
  }

### GET Experience by id API
DELETE https://{{url}}/api/v1/resume/{{resume_id}}/experience/{{experience_id}}/
Authorization: Bearer {{token}}

