# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CORE/grpc/CORE.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'CORE/grpc/CORE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x43ORE/grpc/CORE.proto\x12\x12letraz_server.CORE\x1a\x1bgoogle/protobuf/empty.proto\"v\n\x13HealthCheckResponse\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12:\n\x07\x64\x65tails\x18\x03 \x01(\x0b\x32).letraz_server.CORE.HealthDetailsResponse\"X\n\x15HealthDetailsResponse\x12\x0e\n\x06sentry\x18\x01 \x01(\t\x12\r\n\x05\x63lerk\x18\x02 \x01(\t\x12\n\n\x02\x64\x62\x18\x03 \x01(\t\x12\x14\n\x0cutil_service\x18\x04 \x01(\t2b\n\x0e\x43oreController\x12P\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\'.letraz_server.CORE.HealthCheckResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CORE.grpc.CORE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=73
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=191
  _globals['_HEALTHDETAILSRESPONSE']._serialized_start=193
  _globals['_HEALTHDETAILSRESPONSE']._serialized_end=281
  _globals['_CORECONTROLLER']._serialized_start=283
  _globals['_CORECONTROLLER']._serialized_end=381
# @@protoc_insertion_point(module_scope)
