# Generated by Django 5.1.4 on 2025-01-09 12:47

import RESUME.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CORE', '0001_initial'),
        ('JOB', '0001_initial'),
        ('PROFILE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.CharField(default=RESUME.models.generate_resume_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('base', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JOB.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PROFILE.userinfo')),
            ],
            options={
                'unique_together': {('user_id', 'job_id')},
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('job_title', models.CharField(blank=True, max_length=250, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('flt', 'Full Time'), ('prt', 'Part Time'), ('con', 'Contract'), ('int', 'Internship'), ('fre', 'Freelance'), ('sel', 'Self Employed'), ('vol', 'Volunteer'), ('tra', 'Trainee')], max_length=3, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('started_from_month', models.PositiveSmallIntegerField()),
                ('started_from_year', models.PositiveSmallIntegerField()),
                ('finished_at_month', models.PositiveSmallIntegerField()),
                ('finished_at_year', models.PositiveSmallIntegerField()),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PROFILE.userinfo')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESUME.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=250)),
                ('field_of_study', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=250)),
                ('started_from_month', models.PositiveSmallIntegerField()),
                ('started_from_year', models.PositiveSmallIntegerField()),
                ('finished_at_month', models.PositiveSmallIntegerField()),
                ('finished_at_year', models.PositiveSmallIntegerField()),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PROFILE.userinfo')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESUME.resume')),
            ],
        ),
    ]
