# Generated by Django 5.2.4 on 2025-08-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESUME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
