# Generated by Django 5.1.4 on 2025-07-22 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0003_process'),
        ('JOB', '0002_job_process_job_processing'),
        ('RESUME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CORE.process'),
        ),
        migrations.AddField(
            model_name='resume',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job',
            field=models.ForeignKey(blank=True, help_text="The job the resume is for. (optional in case it's a base resume for the user.)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='JOB.job'),
        ),
    ]
