# Generated by Django 5.1.4 on 2025-01-09 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESUME', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='resume',
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('type', models.CharField(max_length=3)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESUME.resume')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='resume_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RESUME.resumesection'),
        ),
        migrations.AddField(
            model_name='experience',
            name='resume_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RESUME.resumesection'),
        ),
    ]
