# Generated by Django 5.2.4 on 2025-08-03 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0001_initial'),
        ('RESUME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='thumbnail_process',
            field=models.ForeignKey(blank=True, help_text='Current thumbnail generation process', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail_resumes', to='CORE.process'),
        ),
    ]
