# Generated by Django 5.1.4 on 2025-01-09 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0001_initial'),
        ('RESUME', '0002_remove_education_resume_remove_experience_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JOB.job'),
        ),
    ]
