# Generated by Django 5.1.4 on 2025-01-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESUME', '0003_alter_resume_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumesection',
            name='type',
            field=models.CharField(choices=[('edu', 'Education'), ('exp', 'Experience'), ('oth', 'Others')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='resumesection',
            unique_together={('resume', 'index')},
        ),
    ]
