# Generated by Django 5.1.4 on 2025-01-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0001_initial'),
        ('RESUME', '0004_alter_resumesection_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CORE.country'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='finished_at_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='finished_at_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESUME.resumesection'),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_from_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_from_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
