# Generated by Django 5.1.4 on 2025-01-09 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESUME', '0005_alter_education_country_alter_education_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='finished_at_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='finished_at_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resume_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESUME.resumesection'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_from_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_from_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
