# Generated by Django 5.1.4 on 2025-01-09 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0001_initial'),
        ('RESUME', '0006_alter_experience_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='experience',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CORE.country'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(choices=[('flt', 'Full Time'), ('prt', 'Part Time'), ('con', 'Contract'), ('int', 'Internship'), ('fre', 'Freelance'), ('sel', 'Self Employed'), ('vol', 'Volunteer'), ('tra', 'Trainee')], max_length=3),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_title',
            field=models.CharField(max_length=250),
        ),
    ]
