# Generated by Django 5.1.4 on 2025-01-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESUME', '0007_alter_experience_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='resume_section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RESUME.resumesection'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resume_section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RESUME.resumesection'),
        ),
    ]
