# Generated by Django 5.1.4 on 2025-01-24 17:10

import JOB.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(default=JOB.models.generate_job_id, editable=False, help_text='The unique identifier for the job entry.', max_length=25, primary_key=True, serialize=False)),
                ('job_url', models.CharField(blank=True, help_text='The URL of the job posting. (optional)', max_length=1000, null=True)),
                ('title', models.CharField(help_text='The title of the job as mentioned in the job posting. If not available, a meaningful title would be auto-generated.', max_length=250)),
                ('company_name', models.CharField(help_text='The name of the company that posted the job.', max_length=250)),
                ('location', models.CharField(blank=True, help_text='The location of the job as mentioned in the job posting. (optional)', max_length=100, null=True)),
                ('currency', models.CharField(blank=True, help_text='The currency code of the salary. (optional)', max_length=5, null=True)),
                ('salary_max', models.PositiveBigIntegerField(blank=True, help_text='The maximum salary of the job as mentioned in the job posting. (optional)', null=True)),
                ('salary_min', models.PositiveBigIntegerField(blank=True, help_text='The minimum salary of the job as mentioned in the job posting. (optional)', null=True)),
                ('requirements', models.JSONField(blank=True, help_text='An array representation of the requirements of the job as mentioned in the job posting. (optional)', null=True)),
                ('description', models.CharField(blank=True, help_text='The description of the job as mentioned in the job posting. (optional)', max_length=3000, null=True)),
                ('responsibilities', models.JSONField(blank=True, help_text='An array representation of the responsibilities the candidate would be undertaking as mentioned in the job posting. (optional)', null=True)),
                ('benefits', models.JSONField(blank=True, help_text='An array representation of the benefits the candidate would get as mentioned in the job posting. (optional)', null=True)),
            ],
        ),
    ]
