# Generated by Django 5.1.4 on 2025-01-09 12:47

import JOB.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(default=JOB.models.generate_job_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('job_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('salary_max', models.PositiveBigIntegerField(blank=True, null=True)),
                ('salary_min', models.PositiveBigIntegerField(blank=True, null=True)),
                ('requirements', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('responsibilities', models.JSONField(blank=True, null=True)),
                ('benefits', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
