# Generated by Django 5.2.4 on 2025-08-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='processing',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Processing'), ('S', 'Success'), ('F', 'Failure'), ('M', 'Manual'), ('O', 'Other')], help_text='The status of the job as mentioned in the job posting. (optional)', max_length=1, null=True),
        ),
    ]
