# Generated by Django 5.1.4 on 2025-07-22 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0003_process'),
        ('JOB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CORE.process'),
        ),
        migrations.AddField(
            model_name='job',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
